name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (replace with your Node.js version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Start the SSH agent and Add id_rsa key with a password
      - name: Start SSH Agent and Add id_rsa
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SERVER_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          echo "${{ secrets.SERVER_SSH_PASSWORD }}" | ssh-add id_rsa
        env:
          SERVER_SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

      # Deploy to the server using SSH
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/ubuntu/kyungho.info
            git pull origin main
            npm install
            npm run build
            docker-compose up -d --build
          EOF